name: Run community analyzer
description: A composite action that runs either dart-analyze or kube-linter

inputs:
  ref:
    description: "The ref of the community-analyzers-action repository"
    required: true
  analyzer:
    description: "Name of the analyzer to run"
    required: true
  deepsource-dsn:
    description: "The DSN of the DeepSource organization"
    required: true
  path:
    description: "The path of the directory or file to scan"
    default: "."
  output-file:
    description: "The path to the output file"
    default: "./deepsource-report.sarif"
  extra-data-json:
    description: "Extra data as stringified JSON to be passed to the analyzer"
    default: "{}"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout community analyzer files
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: "yash-deepsource/community-analyzers-action"
        path: "./.community-analyzers-action"

    - name: Run dart-analyze
      if: ${{ inputs.analyzer == 'dart-analyze' }}
      uses: ./.community-analyzers-action/src/dart-analyze
      with:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
        extra-data-json: ${{ inputs.extra-data-json }}

    - name: Run kube-linter
      if: ${{ inputs.analyzer == 'kube-linter' }}
      uses: ./.community-analyzers-action/src/kube-linter
      with:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
        extra-data-json: ${{ inputs.extra-data-json }}

    - name: Run cfn-lint
      if: ${{ inputs.analyzer == 'cfn-lint' }}
      uses: ./.community-analyzers-action/src/cfn-lint
      with:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
        extra-data-json: ${{ inputs.extra-data-json }}

    - name: Run slither
      if: ${{ inputs.analyzer == 'slither' }}
      uses: ./.community-analyzers-action/src/slither
      with:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
        extra-data-json: ${{ inputs.extra-data-json }}

    - name: Run solhint
      if: ${{ inputs.analyzer == 'solhint' }}
      uses: ./.community-analyzers-action/src/solhint
      with:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
        extra-data-json: ${{ inputs.extra-data-json }}

    - name: Upload SARIF report to DeepSource
      shell: bash
      run: |
        # Install the CLI
        curl https://deepsource.io/cli | sh

        # Send the report to DeepSource
        ./bin/deepsource report --analyzer ${{ inputs.analyzer }} --analyzer-type community --value-file ${{ inputs.output-file }}

      env:
        DEEPSOURCE_DSN: ${{ inputs.deepsource-dsn }}
