name: Scan with dart-analyze

inputs:
  path:
    description: "The path of the directory or file to scan"
    default: "."
  output-file:
    description: "The path to the output file"
    required: true
  extra-data-json:
    description: "Extra data as stringified JSON to be passed to the analyzer"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ fromJSON(inputs.extra-data-json).sdk }}

    - name: Run Dart Analyze
      shell: bash
      run: dart analyze ${{ inputs.path }} > dart_analyze.txt
      continue-on-error: true

    - name: Dart Analyze to SARIF
      uses: advanced-security/dart-analyzer-sarif@main
      with:
        input: dart_analyze.txt
        output: ${{ inputs.output-file }}
