name: Scan with Solhint

inputs:
  path:
    description: "The path of the directory or file to scan"
    default: "."
  output-file:
    description: "The path to the output file"
    default: "./deepsource-report.sarif"
  extra-data-json:
    description: "Extra data as stringified JSON to be passed to the analyzer"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ fromJSON(inputs.extra-data-json).node-version }}
        node-version-file: ${{ fromJSON(inputs.extra-data-json).node-version-file }}
        cache: ${{ fromJSON(inputs.extra-data-json).cache }}
        cache-dependency-path: ${{ fromJSON(inputs.extra-data-json).cache-dependency-path }}
        registry-url: ${{ fromJSON(inputs.extra-data-json).registry-url }}
        scope: ${{ fromJSON(inputs.extra-data-json).scope }}
        always-auth: ${{ fromJSON(inputs.extra-data-json).always-auth }}

    - name: Run solhint
      shell: bash
      run: |
        npx solhint@{{ fromJSON(inputs.extra-data-json).version }} ${{ inputs.path }} ${CONFIG_PATH:+--config $CONFIG_PATH} ${IGNORE_PATH:+--ignore-path $IGNORE_PATH} --disc --noPrompt --formatter sarif > ${{ inputs.output-file }}
      env:
        CONFIG_PATH: ${{ fromJSON(inputs.extra-data-json).config }}
        IGNORE_PATH: ${{ fromJSON(inputs.extra-data-json).ignore-path }}
      continue-on-error: true
