name: Scan with kube-linter
inputs:
  path:
    description: "The path of the directory or file to scan"
    default: "."
  config:
    description: "The path to the kube-linter config file"
    required: false
  output-file:
    description: "The path to the output file"
    default: "./deepsource-report.sarif"
runs:
  using: "composite"
  steps:
    - name: Scan files with kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      id: kube-linter-action-scan
      with:
        directory: ${{ inputs.path }}
        format: sarif
        output-file: ${{ inputs.output-file }}
      continue-on-error: true
