name: Scan with cfn-lint

inputs:
  path:
    description: "The path of the directory or file to scan"
    default: "./**/*.yaml"
  output-file:
    description: "The path to the output file"
    default: "./deepsource-report.sarif"
  extra-data-json:
    description: "Extra data as stringified JSON to be passed to the analyzer"
    required: false

runs:
  using: "composite"
  steps:
    - name: Scan files with cfn-lint
      uses: scottbrenner/cfn-lint-action@v2
      with:
        version: ${{ fromJSON(inputs.extra-data-json).version }}

    - name: Run cfn-lint
      run: |
        cfn-lint -t ${{ inputs.path }} -f sarif > ${{ inputs.output-file }}
      continue-on-error: true
